# -*- coding: utf-8 -*-
"""VeriAnaliziOdev_1.ipynb adlı not defterinin kopyası

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CXX7dsoauyp7xuuKt9PJy55fkeGqY9-U

1- Girilen sayının pozitif, negatif veya sıfır olduğunu yazan koşul
"""

print("Bir sayı giriniz: ")
sayi = int(input())
if sayi > 0:
    print("Girilen sayı pozitiftir.")
elif sayi < 0:
    print("Girilen sayı negatiftir.")
else:
    print("Girilen sayı sıfırdır.")

"""2- Girilen sayının tek mi çift mi olduğunu yazan koşul"""

print("Bir sayı giriniz: ")
x=int(input())
if x%2==0:
    print("Girilen sayı çifttir.")
else:
    print("Girilen sayı tektir.")

"""3- Girilen nota göre harf aralığını yazan koşul (80-100 A, 60-80 B vs.)"""

print("Not giriniz: ")
notu=int(input())
if notu>=80:
    print("Harf notu: A")
elif notu>=60:
    print("Harf notu: B")
elif notu>=40:
    print("Harf notu: C")

else:
    print("Harf notu: D")

"""4- Girilen ismin karakter sayısı 5den büyükse "uzun bir isminiz var" değilse ismini yazsın"""

print("İsminizi giriniz: ")
isim=input()
if len(isim)>5:
    print("Uzun bir isminiz var.")
else:
    print("İsminiz: ",isim)

"""5- Girilen sayının asal olup olmadığını bulan kod dizisi. (for ve while)"""

print("Bir sayı giriniz: ")
sayi=int(input())

# For döngüsü ile
for i in range(2,sayi):
    if sayi%i==0:
        print("Girilen sayı asal değildir.")
        break
else:
    print("Girilen sayı asaldır.")

# while döngüsü ile
i=2
while i<sayi:
    if sayi%i==0:
        print("Girilen sayı asal değildir.")
        break
    i+=1
else:
    print("Girilen sayı asaldır.")

"""6- Notlar=[45,85,75,50] içinde 75 değerinin indisini yazdıran döngü"""

Notlar=[45,85,75,50]
for i in range(len(Notlar)):
    if Notlar[i]==75:
        print(i)

"""7- Girilen sayının faktöriyelini alalım. (for ve while)"""

print("Bir sayı giriniz: ")
sayi=int(input())

# for döngüsü ile
faktoriyel=1
for i in range(1,sayi+1):
    faktoriyel*=i
print(faktoriyel)

# while döngüsü ile
i=1
fak=1
while i<sayi+1:
    fak*=i
    i+=1
print(faktoriyel)

"""8- Kullanıcıdan pozitif bir sayı bekleyen, pozitifi de gördüğü an bastıran, negatif sayı girildikçe bir daha soran yapı kuralım. (for döngüsü ile)"""

print("Pozitif bir sayı giriniz: ")
sayi=int(input())
for i in iter(int,1):
    if sayi>0:
        print(sayi)
        break
    else:
        print("Pozitif bir sayı giriniz: ")
        sayi=int(input())

"""9- Fonksiyon ile girilen sayının asal olup olmadığını bulan kod dizisi. (for ve while)"""

#for ile
def asal_mi(sayi):
    for i in range(2,sayi):
        if sayi%i==0:
            return False
    return True
print("bir sayı giriniz: ")
sayi=int(input())
sonuc=asal_mi(sayi)
if(sonuc==True):
    print(sayi,"sayısı asaldır.")
else:
    print(sayi,"sayısı asal değildir.")

#while ile
def asal_mi(sayi):
    i=2
    while i<sayi:
        if sayi%i==0:
            return False
        i+=1
    return True
print("bir sayı giriniz: ")
sayi=int(input())
sonuc=asal_mi(sayi)
if(sonuc==True):
    print(sayi,"sayısı asaldır.")
else:
    print(sayi,"sayısı asal değildir.")

"""10- Fonksiyon ile girilen sayının faktöriyelini alalım. (for ve while)"""

#for ile
def Faktöriyel_Hesapla(sayi):
  fak=1
  for i in range(1,sayi+1):
    fak*=i
  return fak

print("Bir sayı giriniz: ")
sayi=int(input())
sonuc=Faktöriyel_Hesapla(sayi)
print(sonuc)

#while ile
def Faktöriyel_Hesapla(sayi):
  fak=1
  i=1
  while i<sayi+1:
    fak*=i
    i+=1
  return fak

print("Bir sayı giriniz: ")
sayi=int(input())
sonuc=Faktöriyel_Hesapla(sayi)
print(sonuc)